In [1]:
import torch

In [3]:
def create_toeplitz_matrix(m):
    N, L = m.shape
    diagonal = torch.arange(N)
    indices = diagonal.view(-1, 1) - diagonal
    b = m[indices]
    
    return b

In [4]:
m = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

toeplitz_matrix = create_toeplitz_matrix(m)

In [5]:
print(toeplitz_matrix)

tensor([[[1, 2, 3],
         [7, 8, 9],
         [4, 5, 6]],

        [[4, 5, 6],
         [1, 2, 3],
         [7, 8, 9]],

        [[7, 8, 9],
         [4, 5, 6],
         [1, 2, 3]]])


In [6]:
def create_toeplitz_matrix(m):
    N, L = m.shape
    b = torch.zeros((N, N))

    for i in range(N):
        for j in range(N):
            if i >= j:
                b[i, j] = m[i - j, 0]

    return b

m = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

toeplitz_matrix = create_toeplitz_matrix(m)
print(toeplitz_matrix)

tensor([[1., 0., 0.],
        [4., 1., 0.],
        [7., 4., 1.]])


In [8]:
def create_toeplitz_matrix(m):
    N, L = m.shape
    diagonal = torch.arange(L)
    indices = diagonal.view(1, -1) - diagonal.view(-1, 1)
    b = m[:, indices]

    return b

m = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

toeplitz_matrix = create_toeplitz_matrix(m)
print(toeplitz_matrix)

tensor([[[1, 2, 3],
         [3, 1, 2],
         [2, 3, 1]],

        [[4, 5, 6],
         [6, 4, 5],
         [5, 6, 4]],

        [[7, 8, 9],
         [9, 7, 8],
         [8, 9, 7]]])


In [10]:
from scipy.linalg import toeplitz

m = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

toeplitz_matrix = toeplitz(m)
print(toeplitz_matrix)

[[1 2 3 4 5 6 7 8 9]
 [2 1 2 3 4 5 6 7 8]
 [3 2 1 2 3 4 5 6 7]
 [4 3 2 1 2 3 4 5 6]
 [5 4 3 2 1 2 3 4 5]
 [6 5 4 3 2 1 2 3 4]
 [7 6 5 4 3 2 1 2 3]
 [8 7 6 5 4 3 2 1 2]
 [9 8 7 6 5 4 3 2 1]]


In [3]:
import torch
import torch.nn as nn
import scipy.linalg as linalg

# Create the attention tensor of shape (1, 1, 128)
attention = torch.ones((1, 1, 128))

# Generate the Toeplitz matrix using scipy.linalg.toeplitz
toeplitz_matrix = linalg.toeplitz(range(128))

# Convert the Toeplitz matrix to a torch tensor
toeplitz_tensor = torch.from_numpy(toeplitz_matrix).float()

# Expand dimensions to match the attention tensor shape
toeplitz_expanded = toeplitz_tensor.expand(1, 1, 128, 128)

# Define the convolution layer with 128 input channels and 128 output channels
conv = nn.Conv2d(128, 128, kernel_size=1, stride=1)

# Perform the 1x1 convolution to multiply the attention tensor with the Toeplitz matrix
result = conv(attention) * toeplitz_expanded

print(result.shape)


RuntimeError: Expected 4-dimensional input for 4-dimensional weight [128, 128, 1, 1], but got 3-dimensional input of size [1, 1, 128] instead

torch.Size([1, 1, 128, 128])